
server:
  port: 1005

spring:
  application:
    name: service-meeting

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

logging:
  level:
    root: info
    com.dl.user.mapper: DEBUG
    org.springframework.web: ERROR
    org.springframework: ERROR