# 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
server:
  port: 7900

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7900/eureka/